version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dream
      - POSTGRES_PASSWORD=dream
      - POSTGRES_DB=dream
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/posgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
